global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 2.0 
  publish_frequency: 1.0
  rolling_window: false 
  always_send_full_costmap: true
  static_map: true
  map_type: costmap

  width: 2.0
  height: 2.0
  resolution: 0.01

  plugins:
    - {name: static_layer,       type: "costmap_2d::StaticLayer"} 
    - {name: obstacle_layer,     type: "costmap_2d::ObstacleLayer"} 
    - {name: inflation_layer,    type: "costmap_2d::InflationLayer"} 
