# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
arm:
  joint_1:
    ID: 1
    Return_Delay_Time: 0
    Profile_Acceleration: 40
    Profile_Velocity: 40
    Position_P_Gain: 1200
    Position_I_Gain: 0
    Position_D_Gain: 0
    Drive_Mode: 0
  joint_2:
    ID: 2
    Return_Delay_Time: 0
    Profile_Acceleration: 40
    Profile_Velocity: 40
    Position_P_Gain: 500
    Position_I_Gain: 15
    Position_D_Gain: 0
    Drive_Mode: 0
  joint2Dual:
    ID: 3
    Return_Delay_Time: 0
    Profile_Acceleration: 40
    Profile_Velocity: 40
    Position_P_Gain: 500
    Position_I_Gain: 15
    Position_D_Gain: 0
    Drive_Mode: 0
  joint_3:
    ID: 4
    Return_Delay_Time: 0
    Profile_Acceleration: 40
    Profile_Velocity: 40
    Position_P_Gain: 780
    Position_I_Gain: 15
    Position_D_Gain: 0
    Drive_Mode: 0
  joint_4:
    ID: 5
    Return_Delay_Time: 0
    Profile_Acceleration: 80
    Profile_Velocity: 80
    Position_P_Gain: 500
    Position_I_Gain: 10
    Position_D_Gain: 0
    Drive_Mode: 0
  joint_5:
    ID: 6
    Return_Delay_Time: 0
    Profile_Acceleration: 80
    Profile_Velocity: 80
    Position_P_Gain: 400
    Position_I_Gain: 0
    Position_D_Gain: 0
    Drive_Mode: 0
gripper:
  gripperMotor:
    ID: 7
    Return_Delay_Time: 0
    Drive_Mode: 0
    Position_P_Gain: 640
    Position_I_Gain: 0
    Position_D_Gain: 3600
camera:
  head_pan_joint:
    ID: 8
    Return_Delay_Time: 0
    Profile_Acceleration: 30
    Profile_Velocity: 10
    Drive_Mode: 0
  head_tilt_joint:
    ID: 9
    Return_Delay_Time: 0
    Profile_Acceleration: 30
    Profile_Velocity: 10
    Drive_Mode: 0
