controller_list:
 - name: locobot_arm/joint_controller
   action_ns: trajectory
   type: FollowJointTrajectory
   default: true
   joints:
     - joint_1
     - joint_2
     - joint_3
     - joint_4
     - joint_5
